### PR TITLE
Fix unit test

### LINKED ISSUE #55: Unit tests on unexpected scenarios
### Scenario/Intent
Run unit tests on a file with API 200 and Synergy hardware variant.

### Steps to Reproduce
Run unit tests on a file with API 200 and Synergy hardware variant.

### Expected Result
I get only the c7000 unit tests for 200, as synergy was not supported in 200.

### Actual Result
It tries to run Synergy with 200 and fails due to uninitialized constant.

### PR DESCRIPTION
**Pull request by abiliogp**
### Description
Fix unit tests on unexpected scenarios 

### Issues Resolved
#55 

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: spec/unit/provider/oneview_connection_template_synergy_spec.rb [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+# limitations under the License.
+################################################################################
+
+require 'spec_helper'
+
+provider_class = Puppet::Type.type(:oneview_connection_template).provider(:synergy)
+api_version = login[:api_version] || 200
+resourcetype = OneviewSDK.resource_named(:ConnectionTemplate, api_version, 'Synergy')
+
+describe provider_class, unit: true do
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_connection_template_synergy_spec.rb]: `, if: login[:api_version] >= 300`

File: spec/unit/provider/oneview_connection_template_synergy_spec.rb [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+################################################################################
+
+require 'spec_helper'
+
+provider_class = Puppet::Type.type(:oneview_connection_template).provider(:synergy)
+api_version = login[:api_version] || 200
+resourcetype = OneviewSDK.resource_named(:ConnectionTemplate, api_version, 'Synergy')
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_connection_template_synergy_spec.rb]: This will try to call Synergy for api 200. Best to to move this declaration to line `24~25` inside the describe provider_class

File: spec/unit/provider/oneview_connection_template_synergy_spec.rb [hunk 3]
```diff
@@ -0,0 +1,77 @@
...
+    let(:provider) { resource.provider }
+
+    let(:instance) { provider.class.instances.first }
+
+    it 'should be an instance of the provider synergy' do
+      expect(provider).to be_an_instance_of Puppet::Type.type(:oneview_connection_template).provider(:synergy)
+    end
+
+    it 'should return that the resource exists' do
+      test = resourcetype.new(@client, name: resource['data']['name'])
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_connection_template_synergy_spec.rb]: test should be inside a `let` so it can be reused and removed from every `it`

File: spec/unit/provider/oneview_connection_template_synergy_spec.rb [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+      allow(resourcetype).to receive(:find_by).and_return([test])
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_connection_template_synergy_spec.rb]: This should be inside a `before_each`

File: spec/unit/provider/oneview_datacenter_synergy_spec.rb [hunk 5]
```diff
@@ -0,0 +1,128 @@
...
+  context 'given the min parameters' do
+    let(:resource) do
+      Puppet::Type.type(:oneview_datacenter).new(
+        name: 'Datacenter',
+        ensure: 'found',
+        provider: 'synergy'
+      )
+    end
+
+    let(:provider) { resource.provider }
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_datacenter_synergy_spec.rb]: No need to redeclare the provider and instance `let`, should just move them out of a specific context.

File: spec/unit/provider/oneview_datacenter_synergy_spec.rb [hunk 6]
```diff
@@ -0,0 +1,128 @@
...
+        ensure: 'present',
+        data:
+            {
+              'name' => 'Datacenter'
+            },
+        provider: 'synergy'
+      )
+    end
+
+    let(:provider) { resource.provider }
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_datacenter_synergy_spec.rb]: Same as previous comment

File: spec/unit/provider/oneview_datacenter_synergy_spec.rb [hunk 7]
```diff
@@ -0,0 +1,128 @@
...
+      expect(provider.exists?).to eq(true)
+    end
+
+    it 'should be able to get the visual content' do
+      visual_content = 'spec/support/fixtures/unit/provider/datacenter_visual_content.json'
+      allow_any_instance_of(resourcetype).to receive(:get_visual_content).and_return(File.read(visual_content))
+      expect(provider.get_visual_content).to eq(true)
+    end
+
+    it 'deletes the resource' do
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_datacenter_synergy_spec.rb:106]: This could have most lines removed from it after the modifications mentioned

File: spec/unit/provider/oneview_drive_enclosure_synergy_spec.rb [hunk 8]
```diff
@@ -15,16 +15,13 @@
 ################################################################################
 
 require 'spec_helper'
-require_relative '../../support/fake_response'
-require_relative '../../shared_context'
 
 provider_class = Puppet::Type.type(:oneview_drive_enclosure).provider(:synergy)
+api_version = login[:api_version] || 200
+resourcetype = OneviewSDK.resource_named(:DriveEnclosure, api_version, 'Synergy')
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_drive_enclosure_synergy_spec.rb]: Move to line `25`

File: spec/unit/provider/oneview_enclosure_group_synergy_spec.rb [hunk 9]
```diff
@@ -0,0 +1,126 @@
...
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+################################################################################
+
+require 'spec_helper'
+
+provider_class = Puppet::Type.type(:oneview_enclosure_group).provider(:synergy)
+api_version = login[:api_version] || 200
+resourcetype = OneviewSDK.resource_named(:EnclosureGroup, api_version, 'Synergy')
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_enclosure_group_synergy_spec.rb]: move to line `25`

File: spec/unit/provider/oneview_enclosure_group_synergy_spec.rb [hunk 10]
```diff
@@ -0,0 +1,126 @@
...
+    let(:provider) { resource.provider }
+
+    let(:instance) { provider.class.instances.first }
+
+    it 'should be an instance of the provider Ruby' do
+      expect(provider).to be_an_instance_of Puppet::Type.type(:oneview_enclosure_group).provider(:synergy)
+    end
+
+    it 'should be able to find the resource' do
+      test = resourcetype.new(@client, resource['data'])
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_enclosure_group_synergy_spec.rb]: Should be inside a `let`

File: spec/unit/provider/oneview_enclosure_group_synergy_spec.rb [hunk 11]
```diff
@@ -0,0 +1,126 @@
...
+      allow(resourcetype).to receive(:find_by).with(anything, resource['data']).and_return([test])
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_enclosure_group_synergy_spec.rb]: line 86~87 should be inside a `before_each`

File: spec/unit/provider/oneview_enclosure_group_synergy_spec.rb [hunk 12]
```diff
@@ -0,0 +1,126 @@
...
+      provider.exists?
+      expect(provider.found).to be
+    end
+
+    it 'runs through the create method' do
+      allow(resourcetype).to receive(:find_by).and_return([])
+      test = resourcetype.new(@client, resource['data'])
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_enclosure_group_synergy_spec.rb]: remove

File: spec/unit/provider/oneview_enclosure_group_synergy_spec.rb [hunk 13]
```diff
@@ -0,0 +1,126 @@
...
+      allow_any_instance_of(resourcetype).to receive(:create).and_return(test)
+      provider.exists?
+      expect(provider.create).to be
+    end
+
+    it 'deletes the resource' do
+      resource['data']['uri'] = '/rest/fake'
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_enclosure_group_synergy_spec.rb:100]: Remove everything except last line

File: spec/unit/provider/oneview_enclosure_synergy_spec.rb [hunk 14]
```diff
@@ -0,0 +1,165 @@
...
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+################################################################################
+
+require 'spec_helper'
+
+provider_class = Puppet::Type.type(:oneview_enclosure).provider(:synergy)
+api_version = login[:api_version] || 200
+resourcetype = OneviewSDK.resource_named(:Enclosure, api_version, 'Synergy')
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_enclosure_synergy_spec.rb]: move to line `25`

File: spec/unit/provider/oneview_enclosure_synergy_spec.rb [hunk 15]
```diff
@@ -0,0 +1,165 @@
...
+
+    it 'should be able to work specifying a name instead of an uri' do
+      resource['data']['enclosureGroupUri'] = 'Test'
+      test = resourcetype.new(@client, resource['data'])
+      allow(OneviewSDK::EnclosureGroup).to receive(:find_by).with(anything, name: resource['data']['enclosureGroupUri']).and_return([test])
+      allow(resourcetype).to receive(:find_by).with(anything, resource['data']).and_return([test])
+      expect(provider.exists?).to be
+    end
+
+    it 'deletes the resource' do
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_enclosure_synergy_spec.rb:102]: refactor this

File: spec/unit/provider/oneview_enclosure_synergy_spec.rb [hunk 16]
```diff
@@ -0,0 +1,165 @@
...
+    it 'should be able to set the refresh state' do
+      allow_any_instance_of(resourcetype).to receive(:script).and_return('Test')
+      expect(provider.get_script).to be
+    end
+
+    it 'should be able to set the refresh state' do
+      expect { provider.get_single_sign_on }.to raise_error(RuntimeError)
+    end
+
+    it 'should be able to work specifying a name instead of an uri' do
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_enclosure_synergy_spec.rb:94]: refactor this

File: spec/unit/provider/oneview_enclosure_synergy_spec.rb [hunk 17]
```diff
@@ -0,0 +1,165 @@
...
+                'username' => 'dcs',
+                'password' => 'dcs',
+                'enclosureGroupUri' => '/rest/',
+                'licensingIntent' => 'OneView'
+              },
+          provider: 'synergy'
+        )
+      end
+
+      it 'creates the resource' do
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_enclosure_synergy_spec.rb:130]: refactor

File: spec/unit/provider/oneview_ethernet_network_synergy_spec.rb [hunk 18]
```diff
@@ -0,0 +1,137 @@
...
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+################################################################################
+
+require 'spec_helper'
+
+provider_class = Puppet::Type.type(:oneview_ethernet_network).provider(:synergy)
+api_version = login[:api_version] || 200
+resourcetype = OneviewSDK.resource_named(:EthernetNetwork, api_version, 'Synergy')
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_ethernet_network_synergy_spec.rb]: move to line `25`

File: spec/unit/provider/oneview_ethernet_network_synergy_spec.rb [hunk 19]
```diff
@@ -0,0 +1,137 @@
...
+
+describe provider_class, unit: true do
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_ethernet_network_synergy_spec.rb]: Missing the guard clause

File: spec/unit/provider/oneview_ethernet_network_synergy_spec.rb [hunk 20]
```diff
@@ -0,0 +1,137 @@
...
+    end
+
+    it 'runs through the create method' do
+      allow(resourcetype).to receive(:find_by).and_return([])
+      allow_any_instance_of(resourcetype).to receive(:create).and_return(resourcetype.new(@client, resource['data']))
+      provider.exists?
+      expect(provider.create).to be
+    end
+
+    it 'deletes the resource' do
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_ethernet_network_synergy_spec.rb:68]: refactor

File: spec/unit/provider/oneview_ethernet_network_synergy_spec.rb [hunk 21]
```diff
@@ -0,0 +1,137 @@
...
+
+  let(:instance) { provider.class.instances.first }
+
+  context 'given the create parameters' do
+    it 'should be an instance of the provider synergy' do
+      expect(provider).to be_an_instance_of Puppet::Type.type(:oneview_ethernet_network).provider(:synergy)
+    end
+
+    it 'should be able to find the resource' do
+      test = resourcetype.new(@client, resource['data'])
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_ethernet_network_synergy_spec.rb]: Again, move test to a `let`

File: spec/unit/provider/oneview_ethernet_network_synergy_spec.rb [hunk 22]
```diff
@@ -0,0 +1,137 @@
...
+      allow(resourcetype).to receive(:find_by).with(anything, resource['data']).and_return([test])
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_ethernet_network_synergy_spec.rb]: Move these to a `before_each`

**Review by fgbulsoni — CHANGES_REQUESTED** [review]
Lots of small changes here and there on the PR, on basically every file. 
Should try to look into the using the guard clause based on `api_version` for every synergy test file to not run against an `api_version` smaller than `300`.
Should move the instance creation, typically named `test` to a `let` instead of duplicating.
Should move the basic `find_by` and `exists?` calls to a `before_each`.
Should generally also look into the it examples and see what is being done and how could those be improved.

**Comment by fgbulsoni** [comment]
Is this PR being updated? I still see `refactor` messages and checking the code it seems like it remains as it was. 
Main things to look out for are: 
- unnecessary `test` declaration inside `it`s, when we are declaring already on `let`
- unecessary mocking 
- lots of different mocks for `find_by`s with different inputs always returning the same `value`
- etc.

File: spec/unit/provider/oneview_datacenter_synergy_spec.rb (hunk 7 above)
Comment (abiliogp) [inline spec/unit/provider/oneview_datacenter_synergy_spec.rb]: If I remove this line, I got this error:
1) Puppet::Type::Oneview_datacenter::ProviderSynergy given the min parameters deletes the resource
     Failure/Error: datacenter.map(&:remove)
     
     OneviewSDK::IncompleteResource:
       Please set uri attribute before interacting with this resource
     # ./lib/puppet/provider/oneview_datacenter/c7000.rb:37:in `map'
     # ./lib/puppet/provider/oneview_datacenter/c7000.rb:37:in `destroy'
     # ./spec/unit/provider/oneview_datacenter_synergy_spec.rb:113:in `block (3 levels) in <top (required)>'

File: spec/unit/provider/oneview_enclosure_group_synergy_spec.rb (hunk 13 above)
Comment (abiliogp) [inline spec/unit/provider/oneview_enclosure_group_synergy_spec.rb]: If I remove this line:

```ruby
it 'deletes the resource' do
      resource['data']['uri'] = '/rest/fake'
      test = resourcetype.new(@client, resource['data'])
      allow(resourcetype).to receive(:find_by).with(anything, resource['data']).and_return([test])
      allow(resourcetype).to receive(:find_by).with(anything, 'name' => resource['data']['name']).and_return([test])
      expect_any_instance_of(OneviewSDK::Client).to receive(:rest_delete).and_return(FakeResponse.new('uri' => '/rest/fake'))
      provider.exists?
      expect(provider.destroy).to be
end
```

I got this error:

1) Puppet::Type::Oneview_datacenter::ProviderSynergy given the min parameters deletes the resource
     Failure/Error: datacenter.map(&:remove)
     
     OneviewSDK::IncompleteResource:
       Please set uri attribute before interacting with this resource
     ./lib/puppet/provider/oneview_datacenter/c7000.rb:37:in `map'
     ./lib/puppet/provider/oneview_datacenter/c7000.rb:37:in `destroy'
     ./spec/unit/provider/oneview_datacenter_synergy_spec.rb:113:in `block (3 levels) in <top (required)>'

File: spec/unit/provider/oneview_enclosure_synergy_spec.rb (hunk 16 above)
Comment (abiliogp) [reply spec/unit/provider/oneview_enclosure_synergy_spec.rb:94]: What you want to change?

File: spec/unit/provider/oneview_enclosure_synergy_spec.rb (hunk 15 above)
Comment (abiliogp) [inline spec/unit/provider/oneview_enclosure_synergy_spec.rb]: Same as above

File: spec/unit/provider/oneview_enclosure_synergy_spec.rb (hunk 17 above)
Comment (abiliogp) [reply spec/unit/provider/oneview_enclosure_synergy_spec.rb:130]: Ok, make sense! :+1:

File: spec/unit/provider/oneview_datacenter_synergy_spec.rb (hunk 7 above)
Comment (abiliogp) [reply spec/unit/provider/oneview_datacenter_synergy_spec.rb:106]: Are you talking about the :findby?

File: spec/unit/provider/oneview_enclosure_synergy_spec.rb [hunk 23]
```diff
@@ -0,0 +1,154 @@
...
+      test = resourcetype.new(@client, resource['data'])
+      allow(OneviewSDK::EnclosureGroup).to receive(:find_by).with(anything, name: resource['data']['enclosureGroupUri']).and_return([test])
+      allow(resourcetype).to receive(:find_by).with(anything, resource['data']).and_return([test])
+      expect(provider.exists?).to be
+    end
+
+    it 'deletes the resource' do
+      resource['data']['uri'] = '/rest/fake'
+      test = resourcetype.new(@client, resource['data'])
+      allow(resourcetype).to receive(:find_by).with(anything, resource['data']).and_return([test])
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_enclosure_synergy_spec.rb:105]: no need for multiple find_bys for different inputs and same return, just leave one without `with`

File: spec/unit/provider/oneview_enclosure_synergy_spec.rb [hunk 24]
```diff
@@ -0,0 +1,154 @@
...
+      allow(resourcetype).to receive(:find_by).with(anything, 'name' => resource['data']['name']).and_return([test])
+      expect_any_instance_of(OneviewSDK::Client).to receive(:rest_delete).and_return(FakeResponse.new('uri' => '/rest/fake'))
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_enclosure_synergy_spec.rb:107]: testing rest_delete is definitely not what we want here

File: spec/unit/provider/oneview_enclosure_synergy_spec.rb [hunk 25]
```diff
@@ -0,0 +1,154 @@
...
+                'password' => 'dcs',
+                'enclosureGroupUri' => '/rest/',
+                'licensingIntent' => 'OneView'
+              },
+          provider: 'synergy'
+        )
+      end
+
+      it 'creates the resource' do
+        allow(resourcetype).to receive(:find_by).with(anything, 'name' => resource['data']['name']).and_return([])
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_enclosure_synergy_spec.rb:131]: no need for the `with`

File: spec/unit/provider/oneview_enclosure_synergy_spec.rb (hunk 23 above)
Comment (fgbulsoni) [reply spec/unit/provider/oneview_enclosure_synergy_spec.rb:105]: Actually, no need for any find_by, this should be in the `before_each` block, as well as the test declaration

File: spec/unit/provider/oneview_enclosure_synergy_spec.rb [hunk 26]
```diff
@@ -0,0 +1,154 @@
...
+        unique_id = { 'uri' => '/rest/fake', 'name' => 'Puppet_Test_Enclosure' }
+        resource['data']['uri'] = '/rest/fake'
+        resource['data']['op'] = 'fake_op'
+        resource['data']['path'] = 'fake_path'
+        resource['data']['value'] = 'fake_value'
+        patch_data = { 'op' => 'fake_op', 'path' => 'fake_path', 'value' => 'fake_value' }
+        test = resourcetype.new(@client, resource['data'])
+        allow(resourcetype).to receive(:find_by).with(anything, resource['data']).and_return([test])
+        allow(resourcetype).to receive(:find_by).with(anything, unique_id).and_return([test])
+        expect_any_instance_of(OneviewSDK::Client).to receive(:rest_patch)
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_enclosure_synergy_spec.rb:147]: we do not want to test rest_ calls, mock the sdk method and clean up the test

File: spec/unit/provider/oneview_ethernet_network_synergy_spec.rb [hunk 27]
```diff
@@ -0,0 +1,137 @@
...
+      allow_any_instance_of(resourcetype).to receive(:create).and_return(test)
+      provider.exists?
+      expect(provider.create).to be
+    end
+
+    it 'deletes the resource' do
+      resource['data']['uri'] = '/rest/fake'
+      test = resourcetype.new(@client, resource['data'])
+      allow(resourcetype).to receive(:find_by).with(anything, resource['data']).and_return([test])
+      expect_any_instance_of(OneviewSDK::Client).to receive(:rest_delete).and_return(FakeResponse.new('uri' => '/rest/fake'))
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_ethernet_network_synergy_spec.rb:72]: we do not want to be testing rest_ calls

File: spec/unit/provider/oneview_fcoe_network_synergy_spec.rb [hunk 28]
```diff
@@ -0,0 +1,80 @@
...
+      allow(resourcetype).to receive(:find_by).and_return([test])
+      expect(instance).to be
+    end
+
+    it 'deletes the resource' do
+      resource['data']['uri'] = '/rest/fake'
+      test = resourcetype.new(@client, resource['data'])
+      allow(resourcetype).to receive(:find_by).with(anything, resource['data']).and_return([test])
+      allow(resourcetype).to receive(:find_by).with(anything, 'name' => resource['data']['name']).and_return([test])
+      expect_any_instance_of(OneviewSDK::Client).to receive(:rest_delete).and_return(FakeResponse.new('uri' => '/rest/fake'))
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_fcoe_network_synergy_spec.rb:75]: again, no rest_ calls

File: spec/unit/provider/oneview_firmware_driver_synergy_spec.rb [hunk 29]
```diff
@@ -0,0 +1,108 @@
...
+      allow_any_instance_of(resourcetype).to receive(:create).and_return(test)
+      provider.exists?
+      expect(provider.create).to be
+    end
+
+    it 'should delete the Firmware Driver' do
+      resource['data']['uri'] = '/rest/firmware-drivers/fake'
+      test = resourcetype.new(@client, resource['data'])
+      allow(resourcetype).to receive(:find_by).with(anything, resource['data']).and_return([test])
+      expect_any_instance_of(OneviewSDK::Client).to receive(:rest_delete).and_return(FakeResponse.new('uri' => '/rest/fake'))
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_firmware_driver_synergy_spec.rb:96]: rest_...

**Review by fgbulsoni — CHANGES_REQUESTED** [review]
I still see many methods that need refactoring.
1. We should not be calling nor mocking the rest methods, just the sdk methods
2. If we have the test in a `let` block, and the find_by already in a `before_each` block (which we SHOULD!), we should not be calling them inside the tests unless absolutely necessary for whatever reason.
3. when mocking the sdk methods, tests should become a lot simpler, so there's also no need for lenghty `it` blocks which declare a lot of stuff inside resource, either make a different resource or those assignments should not be needed.

**Review by fgbulsoni — APPROVED** [review]
