### PR TITLE
Oneview_server_hardware API300 Support

### LINKED ISSUE #24: Server Hardware API300 Support
### Scenario/Intent
Use Oneview_server_hardware with API 300 on the Synergy and C7000 hardware variants

### Environment Details
 - **Puppet module for HPE OneView Version:** 2.0.0
 - **OneView SDK Version:** 3.0.0+
 - **OneView Appliance Version:** 3.0.0
 - **OneView Client API Version:** 300
 - **Puppet Version:** 4.0.0+
 - **Ruby Version:** 2.2.6
 - **Platform:** Windows/CentOS

### Steps to Reproduce
1- Create a login file with api_version = 300 and hardware_variant = "C7000" or "Synergy"
2- Create a manifest in which I call the Oneview_server_hardware resource

### Expected Result
Should use the API 300 of the chosen hardware variant to perform any actions

### Actual Result
Uses the API 200 of the C7000 hardware variant to perform all actions.

### PR DESCRIPTION
**Pull request by fgbulsoni**
### Description
Extends support for API300 to the Server Hardware resource

### Issues Resolved
#24 

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass (`$ rake test`).
- [X] New functionality has been documented in the README if applicable.
  - [X] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: spec/unit/provider/oneview_server_hardware_c7000_spec.rb [hunk 1]
```diff
@@ -0,0 +1,204 @@
...
+# See the License for the specific language governing permissions and
+# limitations under the License.
+################################################################################
+
+require 'spec_helper'
+
+provider_class = Puppet::Type.type(:oneview_server_hardware).provider(:c7000)
+api_version = login[:api_version] || 200
+resource_name = 'ServerHardware'
+resourcetype = if api_version == 200
```
Comment (marikrg) [inline spec/unit/provider/oneview_server_hardware_c7000_spec.rb:22]: Please help me understand. Should we add this verification only for the resources which have differences across API versions?

Comment (fgbulsoni) [reply spec/unit/provider/oneview_server_hardware_c7000_spec.rb:22]: Should be good to add to any/all C7000 unit tests.
It makes sure we're calling 'OneviewSDK::API200::Resource_X' or 'OneviewSDK::API300::C7000::Resource_X'.
This helps prevent 2 cases:
- 1. Case where your ONEVIEW_AUTH_FILE is pointing to a file with api version 200 and it tries to use 'OneviewSDK::API200::C7000::Resource_X', which is an invalid namespace.
- 2. Case where you are using OneviewSDK::Resource_X directly and it calls the default OneviewSDK::API200::Resource_X behind the scenes, so that the actual api that we want tested is not really being tested.

There are other ways to do this as well, this is just one way.

File: lib/puppet/provider/oneview_server_hardware/c7000.rb [hunk 2]
```diff
@@ -14,59 +14,43 @@
...
   end
 
   # Provider methods
   def exists?
     @data = data_parse
     empty_data_check
     data_parse_for_general
+    %w(from op path value).each { |key| @patch_tags[key] = @data.delete(key) if @data[key] }
+    return false unless @patch_tags.empty?
     !@resourcetype.find_by(@client, @data).empty?
```
Comment (tmiotto) [inline lib/puppet/provider/oneview_server_hardware/c7000.rb]: Like... `#any?`

File: lib/puppet/provider/oneview_server_hardware/c7000.rb [hunk 3]
```diff
@@ -14,59 +14,43 @@
...
-    end
+    @patch_tags = {}
   end
 
   # Provider methods
   def exists?
     @data = data_parse
     empty_data_check
     data_parse_for_general
+    %w(from op path value).each { |key| @patch_tags[key] = @data.delete(key) if @data[key] }
```
Comment (tmiotto) [inline lib/puppet/provider/oneview_server_hardware/c7000.rb]: Move to general :taco:

File: lib/puppet/provider/oneview_server_hardware/c7000.rb [hunk 4]
```diff
@@ -14,59 +14,43 @@
...
+    return false unless @patch_tags.empty?
```
Comment (tmiotto) [inline lib/puppet/provider/oneview_server_hardware/c7000.rb]: You can use `return banana if @potato_hash.any?`. It's more intuitive.

File: lib/puppet/provider/oneview_server_hardware/c7000.rb (hunk 3 above)
Comment (fgbulsoni) [reply lib/puppet/provider/oneview_server_hardware/c7000.rb]: Moved to general :taco:
