### PR TITLE
Oneview_sas_logical_interconnect API300 Support

### LINKED ISSUE #71: SAS Logical Interconnect API300 Support
### Scenario/Intent
Use the SAS Logical Interconnect resource from this module

### Environment Details
-**Puppet module for HPE OneView Version:** 2.0.0
-**OneView SDK Version:** 3.1.0
-**OneView Appliance Version:** 3.0
-**OneView Client API Version:** 300
-**Puppet Version:** 4.8
-**Ruby Version:** 2.2.6
-**Platform:** Windows

### Steps to Reproduce
Try to call the resource Oneview_sas_logical_interconnect

### Expected Result
To be able to use the resource to create, update and delete SAS Logical Interconnects on OneView

### Actual Result
Resource not implemented / Could not find the Oneview_sas_logical_interconnect type

### PR DESCRIPTION
**Pull request by fgbulsoni**
### Description
Extends support for API300 to the Oneview_sas_logical_interconnect  resource

### Issues Resolved
#71 

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass (`$ rake test`).
- [X] New functionality has been documented in the README if applicable.
  - [X] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: spec/unit/provider/oneview_sas_logical_interconnect_spec.rb [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+    it 'should be able to run self.instances' do
+      expect(instance).to be
+    end
+
+    it 'should raise an error for unsupported ensure methods' do
+      expect { provider.create }.to raise_error(/This resource relies on others to be created./)
+      expect { provider.destroy }.to raise_error(/This resource relies on others to be destroyed./)
+    end
+
+    it 'should find the resource' do
```
Comment (abiliogp) [inline spec/unit/provider/oneview_sas_logical_interconnect_spec.rb:72]: Is it necessary?

Comment (fgbulsoni) [reply spec/unit/provider/oneview_sas_logical_interconnect_spec.rb:72]: Kind of, doesn't hurt and covers a functionality expected of the type.

**Review by abiliogp — APPROVED** [review]

**Review by marikrg — APPROVED** [review]
