### PR TITLE
Extends support of Oneview_volume for API300

### LINKED ISSUE #33: Volume API300 Support
### Scenario/Intent
Use Oneview_volume with API 300 on the Synergy and C7000 hardware variants

### Environment Details
 - **Puppet module for HPE OneView Version:** 2.0.0
 - **OneView SDK Version:** 3.0.0+
 - **OneView Appliance Version:** 3.0.0
 - **OneView Client API Version:** 300
 - **Puppet Version:** 4.0.0+
 - **Ruby Version:** 2.2.6
 - **Platform:** Windows/CentOS

### Steps to Reproduce
1- Create a login file with api_version = 300 and hardware_variant = "C7000" or "Synergy"
2- Create a manifest in which I call the Oneview_volume resource

### Expected Result
Should use the API 300 of the chosen hardware variant to perform any actions

### Actual Result
Uses the API 200 of the C7000 hardware variant to perform all actions.

### PR DESCRIPTION
**Pull request by marikrg**
### Description
Volume API300 Support

### Issues Resolved
#33 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: lib/puppet/provider/oneview_volume/c7000.rb [hunk 1]
```diff
@@ -14,33 +14,15 @@
...
-      data = line.inspect
-      new(name: name,
-          ensure: :present,
-          data: data)
-    end
-  end
+  confine true: login[:hardware_variant] == 'C7000'
 
   # Provider methods
   def exists?
```
Comment (fgbulsoni) [inline lib/puppet/provider/oneview_volume/c7000.rb:28]: This can be reduced using super([:found, :get_attachable_volumes, :get_extra_managed_volume_paths])

File: spec/unit/provider/oneview_volume_c7000_spec.rb [hunk 2]
```diff
@@ -18,7 +18,7 @@
 require_relative '../../support/fake_response'
 require_relative '../../shared_context'
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_volume_c7000_spec.rb:20]: line 85 of 'lib/puppet/provider/oneview_volume/c7000.rb' is not being touched by this file. 
Should add a ``get_snapshot`` which has a ``name`` so that we reach 100% path coverage

**Review by fgbulsoni — CHANGES_REQUESTED** [review]
Looks good, minor improvements listed.

**Comment by marikrg** [comment]
@fgbulsoni Done! I made the changes you suggested. Can you check again?

**Review by fgbulsoni — APPROVED** [review]

File: spec/unit/provider/oneview_volume_c7000_spec.rb [hunk 3]
```diff
@@ -18,7 +18,7 @@
...
 
-provider_class = Puppet::Type.type(:oneview_volume).provider(:oneview_volume)
+provider_class = Puppet::Type.type(:oneview_volume).provider(:c7000)
 resourcetype = OneviewSDK::Volume
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_volume_c7000_spec.rb]: could add the 
```ruby
api_version = login[:api_version] || 200
resource_name = 'Volume'
resourcetype = if api_version == 200
                 Object.const_get("OneviewSDK::API#{api_version}::#{resource_name}")
               else
                 Object.const_get("OneviewSDK::API#{api_version}::C7000::#{resource_name}")
               end
```
code here to deal with different values

File: spec/unit/provider/oneview_volume_synergy_spec.rb [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+################################################################################
+
+require 'spec_helper'
+require_relative '../../support/fake_response'
+require_relative '../../shared_context'
+
+provider_class = Puppet::Type.type(:oneview_volume).provider(:synergy)
+resourcetype = OneviewSDK::Volume
+
+describe provider_class, unit: true do
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_volume_synergy_spec.rb]: would be good to add 
```ruby
if: api_version > 300
```
here

File: spec/unit/provider/oneview_volume_synergy_spec.rb [hunk 5]
```diff
@@ -0,0 +1,121 @@
...
+# See the License for the specific language governing permissions and
+# limitations under the License.
+################################################################################
+
+require 'spec_helper'
+require_relative '../../support/fake_response'
+require_relative '../../shared_context'
+
+provider_class = Puppet::Type.type(:oneview_volume).provider(:synergy)
+resourcetype = OneviewSDK::Volume
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_volume_synergy_spec.rb]: would be good to change to
```ruby
resource_name = 'Volume'
resourcetype = Object.const_get("OneviewSDK::API#{api_version}::Synergy::#{resource_name}") unless api_version < 300
```
here

**Review by fgbulsoni — CHANGES_REQUESTED** [review]

**Review by fgbulsoni — APPROVED** [review]

**Comment by marikrg** [comment]
Fixed issue #33
