### PR TITLE
Oneview_storage_pool API300 Support

### LINKED ISSUE #28: Storage Pool API300 Support
### Scenario/Intent
Use Oneview_storage_pool with API 300 on the Synergy and C7000 hardware variants

### Environment Details
 - **Puppet module for HPE OneView Version:** 2.0.0
 - **OneView SDK Version:** 3.0.0+
 - **OneView Appliance Version:** 3.0.0
 - **OneView Client API Version:** 300
 - **Puppet Version:** 4.0.0+
 - **Ruby Version:** 2.2.6
 - **Platform:** Windows/CentOS

### Steps to Reproduce
1- Create a login file with api_version = 300 and hardware_variant = "C7000" or "Synergy"
2- Create a manifest in which I call the Oneview_storage_pool resource

### Expected Result
Should use the API 300 of the chosen hardware variant to perform any actions

### Actual Result
Uses the API 200 of the C7000 hardware variant to perform all actions.

### PR DESCRIPTION
**Pull request by fgbulsoni**
### Description
Extends support of Oneview_storage_pool to API300 and few quality of life improvements on common methods

### Issues Resolved
#28 

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass (`$ rake test`).
- [X] New functionality has been documented in the README if applicable.
  - [X] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: lib/puppet/provider/oneview_resource.rb [hunk 1]
```diff
@@ -95,8 +95,9 @@ def create(action = :create)
     end
 
     # TODO: Would be awesome to have this working for everything/most types. Future improvement. Leaving as is in the meanwhile for filler.
-    def destroy
-      get_single_resource_instance.delete
+    def destroy(action = :delete)
+      get_single_resource_instance.delete if action == :delete
+      get_single_resource_instance.remove if action == :remove
```
Comment (tmiotto) [inline lib/puppet/provider/oneview_resource.rb]: What if action is neither `:delete` nor `:remove`?

**Review by tmiotto — APPROVED** [review]
