### PR TITLE
Extending support of the Oneview_volume_attachment resource type to A…

### LINKED ISSUE #34: Volume Attachment API300 Support
### Scenario/Intent
Use Oneview_volume_attachment with API 300 on the Synergy and C7000 hardware variants

### Environment Details
 - **Puppet module for HPE OneView Version:** 2.0.0
 - **OneView SDK Version:** 3.0.0+
 - **OneView Appliance Version:** 3.0.0
 - **OneView Client API Version:** 300
 - **Puppet Version:** 4.0.0+
 - **Ruby Version:** 2.2.6
 - **Platform:** Windows/CentOS

### Steps to Reproduce
1- Create a login file with api_version = 300 and hardware_variant = "C7000" or "Synergy"
2- Create a manifest in which I call the Oneview_volume_attachment resource

### Expected Result
Should use the API 300 of the chosen hardware variant to perform any actions

### Actual Result
Uses the API 200 of the C7000 hardware variant to perform all actions.

### PR DESCRIPTION
**Pull request by abiliogp**
Extending support of the Oneview_volume_attachment resource type to API300 on C7000 and Synergy

### Description
Adds support to the Oneview_volume_attachment resource

### Issues Resolved
Fixes #34

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: lib/puppet/provider/oneview_volume_attachment/c7000.rb [hunk 1]
```diff
@@ -14,35 +14,23 @@
...
-Puppet::Type.type(:oneview_volume_attachment).provide(:oneview_volume_attachment) do
   mk_resource_methods
 
   def initialize(*args)
     super(*args)
-    @client = OneviewSDK::Client.new(login)
-    @resourcetype = OneviewSDK::VolumeAttachment
     # Initializes the data so it is parsed only on exists and accessible throughout the methods
     # This is not set here due to the 'resources' variable not being accessible in initialize
     @data = {}
```
Comment (fgbulsoni) [inline lib/puppet/provider/oneview_volume_attachment/c7000.rb]: super already initializes @data, remove

File: lib/puppet/provider/oneview_volume_attachment/c7000.rb [hunk 2]
```diff
@@ -14,35 +14,23 @@
 # limitations under the License.
 ################################################################################
 
-require_relative '../login'
-require_relative '../common'
-require 'oneview-sdk'
+require_relative '../oneview_resource'
+
+Puppet::Type::Oneview_volume_attachment.provide :c7000, parent: Puppet::OneviewResource do
+  desc 'Provider for OneView Volume Attachment using the C7000 variant of the OneView API'
```
Comment (fgbulsoni) [inline lib/puppet/provider/oneview_volume_attachment/c7000.rb]: Provider for OneView Volume Attachment**s**  (...)

**Review by fgbulsoni — CHANGES_REQUESTED** [review]
Few comments. 
Missing integration tests, are they being run?
Also make sure the sample is able to run.

File: spec/unit/provider/oneview_volume_attachment_synergy_spec.rb [hunk 3]
```diff
@@ -0,0 +1,146 @@
...
+# limitations under the License.
+################################################################################
+
+provider_class = Puppet::Type.type(:oneview_volume_attachment).provider(:synergy)
+
+api_version = login[:api_version] || 200
+resource_name = 'VolumeAttachment'
+resourcetype = Object.const_get("OneviewSDK::API#{api_version}::Synergy::#{resource_name}") unless api_version < 300
+
+describe provider_class, unit: true do
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_volume_attachment_synergy_spec.rb]:
```ruby
describe provider_class, unit: true, if: login[api_version] >= 300 do 
```

File: spec/unit/provider/oneview_volume_attachment_synergy_spec.rb [hunk 4]
```diff
@@ -0,0 +1,146 @@
...
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+################################################################################
+
+provider_class = Puppet::Type.type(:oneview_volume_attachment).provider(:synergy)
+
+api_version = login[:api_version] || 200
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_volume_attachment_synergy_spec.rb:19]: This line and the two bellow could be moved to after the `describe`

**Review by fgbulsoni — CHANGES_REQUESTED** [review]
Integration tests?

File: lib/puppet/provider/oneview_volume_attachment/c7000.rb [hunk 5]
```diff
@@ -14,35 +14,22 @@
...
+  confine true: login[:hardware_variant] == 'C7000'
 
-Puppet::Type.type(:oneview_volume_attachment).provide(:oneview_volume_attachment) do
   mk_resource_methods
 
   def initialize(*args)
     super(*args)
-    @client = OneviewSDK::Client.new(login)
-    @resourcetype = OneviewSDK::VolumeAttachment
     # Initializes the data so it is parsed only on exists and accessible throughout the methods
```
Comment (fgbulsoni) [inline lib/puppet/provider/oneview_volume_attachment/c7000.rb]: leftover comments, should remove

File: spec/integration/provider/oneview_volume_attachment_synergy_spec.rb [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+################################################################################
+
+# NOTE: For all tests in this spec to pass, the volume attachment specified must
+# have unmanaged volumes in it.
+
+require 'spec_helper'
+require File.expand_path(File.join(File.dirname(__FILE__), '../../../lib/puppet/provider/', 'login'))
```
Comment (fgbulsoni) [inline spec/integration/provider/oneview_volume_attachment_synergy_spec.rb]:
```ruby
require_relative '../../../lib/puppet/provider/login'
```

**Review by fgbulsoni — APPROVED** [review]
