### PR TITLE
Removed duplicate tests and direct rest call mocks

### LINKED ISSUE #123: Remove rest call from tests
### Scenario/Intent
Some unit test use rest call

-datacenter_c7000
-datacenter_synergy
-enclosure_c7000
-enclosure_synergy
-enclosure_group_c7000
-enclosure_group_synergy
-ethernet_network_c7000
-ethernet_network_synergy
-fcoe_network_c7000
-fcoe_network_synergy
-firmware_driver_c7000
-firmware_driver_synergy
-rack_c7000
-rack_synergy
-san_manager_c7000
-san_manager_synergy
-server_hardware_c7000
-server_hardware_synergy
-switch_c7000
-uplink_set_c7000
-uplink_set_synergy

### Environment Details
-**Puppet module for HPE OneView Version:** 2.2.0
-**OneView SDK Version:** 3.1.0
-**OneView Appliance Version:** 3.0
-**OneView Client API Version:** 300
-**Puppet Version:** 4.8
-**Ruby Version:** 2.2.6
-**Platform:** Windows/Linux

### Steps to Reproduce
-Not applied 

### Expected Result
-Remove rest call from tests

### Actual Result
-Not applied

### PR DESCRIPTION
**Pull request by fgbulsoni**
### Description
Removed duplicate tests, direct rest call mocks and improved coverage

- Reduced redundant unit tests
- Removed all mocks of direct `rest_ calls` to the appliance
- Updated integration tests to require the `--tag integration` to run
- Updated unit tests to not require the `--tag unit` and be run by default
- Removed unused code from `firmware_driver` `uri_parser` method

### Issues Resolved
#123 

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass (`$ rake test`).
- [X] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: lib/puppet/provider/oneview_interconnect/c7000.rb [hunk 1]
```diff
@@ -54,13 +54,7 @@ def get_types
...
   def get_statistics
     Puppet.notice("\n\nInterconnect Statistics\n")
-    if @statistics
-      @statistics['portName'] = nil unless @statistics['portName']
-      @statistics['subportNumber'] = nil unless @statistics['subportNumber']
-      pretty get_single_resource_instance.statistics(@statistics['portName'], @statistics['subportNumber'])
-    else
-      get_single_resource_instance.statistics
-    end
+    pretty get_single_resource_instance.statistics(@statistics['portName'], @statistics['subportNumber'])
```
Comment (ricardogpsf) [inline lib/puppet/provider/oneview_interconnect/c7000.rb:57]: good! =)

**Review by ricardogpsf — APPROVED** [review]
