### PR TITLE
Server Profile Template API300 Support

### LINKED ISSUE #27: Server Profile Template API300 Support
### Scenario/Intent
Use Oneview_server_profile_template with API 300 on the Synergy and C7000 hardware variants

### Environment Details
 - **Puppet module for HPE OneView Version:** 2.0.0
 - **OneView SDK Version:** 3.0.0+
 - **OneView Appliance Version:** 3.0.0
 - **OneView Client API Version:** 300
 - **Puppet Version:** 4.0.0+
 - **Ruby Version:** 2.2.6
 - **Platform:** Windows/CentOS

### Steps to Reproduce
1- Create a login file with api_version = 300 and hardware_variant = "C7000" or "Synergy"
2- Create a manifest in which I call the Oneview_server_profile_template resource

### Expected Result
Should use the API 300 of the chosen hardware variant to perform any actions

### Actual Result
Uses the API 200 of the C7000 hardware variant to perform all actions.

### PR DESCRIPTION
**Pull request by marikrg**
### Description
Use Oneview_server_profile_template with API 300 on the Synergy and C7000 hardware variants.

### Issues Resolved
#27 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: lib/puppet/provider/oneview_server_profile_template/c7000.rb [hunk 1]
```diff
@@ -40,14 +33,6 @@ def create
     @resourcetype.new(@client, @data).create
```
Comment (fgbulsoni) [inline lib/puppet/provider/oneview_server_profile_template/c7000.rb]: create seems like it could be removed.

File: spec/unit/provider/oneview_server_profile_template_c7000_spec.rb [hunk 2]
```diff
@@ -0,0 +1,150 @@
...
+    let(:resource) do
+      Puppet::Type.type(:oneview_server_profile_template).new(
+        name: 'spt',
+        ensure: 'present',
+        data:
+            {
+              'name'                  => 'SPT',
+              'enclosureGroupUri'     => '/rest/',
+              'serverHardwareTypeUri' => '/rest/',
+              'type'                  => 'ServerProfileTemplateV1'
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_server_profile_template_c7000_spec.rb]: type should not be included

File: spec/unit/provider/oneview_server_profile_template_c7000_spec.rb [hunk 3]
```diff
@@ -0,0 +1,150 @@
...
+      expect(provider).to be_an_instance_of Puppet::Type.type(:oneview_server_profile_template).provider(:c7000)
+    end
+
+    it 'should run exists? and return the resource does not exist' do
+      allow(resourcetype).to receive(:find_by).and_return([])
+      expect(provider.exists?).to eq(false)
+    end
+
+    it 'should return the resource has been found' do
+      test = resourcetype.new(@client, resource['data'])
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_server_profile_template_c7000_spec.rb]: Could move this `test` variable to a `let` in order to prevent repetition

File: spec/unit/provider/oneview_server_profile_template_c7000_spec.rb [hunk 4]
```diff
@@ -0,0 +1,150 @@
...
+    it 'should be able to create the resource' do
+      allow(resourcetype).to receive(:find_by).and_return([])
+      allow_any_instance_of(resourcetype).to receive(:create).and_return(resourcetype.new(@client, resource['data']))
+      expect(provider.exists?).to eq(false)
+      expect(provider.create).to be
+    end
+
+    it 'should be able to create a server profile with default name using the template' do
+      test = resourcetype.new(@client, resource['data'])
+      allow(resourcetype).to receive(:find_by).with(anything, resource['data']).and_return([test])
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_server_profile_template_c7000_spec.rb]: Should add this `allow` and other similar to a `before(:each)` method in order to avoid repetition

File: spec/unit/provider/oneview_server_profile_template_c7000_spec.rb [hunk 5]
```diff
@@ -0,0 +1,150 @@
...
+      allow_any_instance_of(resourcetype).to receive(:get_transformation).and_return(fake_server_profile)
+      expect(provider.get_transformation).to be
+    end
+
+    it 'should be able to delete the resource' do
+      resource['data'] = { 'name' => 'SPT', 'uri' => '/rest/fake' }
+      test = resourcetype.new(@client, resource['data'])
+      allow(resourcetype).to receive(:find_by).with(anything, resource['data']).and_return([test])
+      allow(resourcetype).to receive(:find_by).with(anything, name: resource['data']['name']).and_return([test])
+      expect_any_instance_of(OneviewSDK::Client).to receive(:rest_delete).and_return(FakeResponse.new('uri' => '/rest/fake'))
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_server_profile_template_c7000_spec.rb]: Should use instances of `resourcetype` instead of `OneviewSDK::Client` and receive `:delete` instead of `:rest_delete`

**Review by fgbulsoni — CHANGES_REQUESTED** [review]

File: spec/unit/provider/oneview_server_profile_template_c7000_spec.rb [hunk 6]
```diff
@@ -60,15 +65,11 @@
     end
 
     it 'should return the resource has been found' do
-      test = resourcetype.new(@client, resource['data'])
-      allow(resourcetype).to receive(:find_by).and_return([test])
       provider.exists?
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_server_profile_template_c7000_spec.rb]: also move the `provider.exists?` from the `it` tests to the `before(:each)`

**Review by fgbulsoni — APPROVED** [review]
