### PR TITLE
Remove leftover code and add parent class to parentless resources

### LINKED ISSUE #82: Reduce code duplication and complexity
### Scenario/Intent
Reduce code duplication and complexity, while maintaining functionality.

### Environment Details
-**Puppet module for HPE OneView Version:** 2.0.0
-**OneView SDK Version:** 3.1.0
-**OneView Appliance Version:** 3.0
-**OneView Client API Version:** 300
-**Puppet Version:** 4.8
-**Ruby Version:** 2.2.6
-**Platform:** Windows

### Steps to Reproduce
Check the code, mainly on the resources which currently do not use a parent class.

### Expected Result
Should have the least amount of code duplication, as it is possible.

### Actual Result
Some classes currently are not yet inheriting from Oneview_resource and thus have a lot of code duplication inside them. 
Also, others were implemented while the Oneview_resource class was being improved, and could also have many improvements.

### PR DESCRIPTION
**Pull request by fgbulsoni**
### Description
Removing leftover unecessary code and adding the parent class to thefirst resources developed

### Issues Resolved
#82 

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass (`$ rake test`).
- [X] New functionality has been documented in the README if applicable.
  - [X] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: lib/puppet/provider/oneview_network_set/c7000.rb [hunk 1]
```diff
@@ -48,19 +39,6 @@ def exists?
     !@resourcetype.find_by(@client, @data).empty?
```
Comment (tmiotto) [inline lib/puppet/provider/oneview_network_set/c7000.rb:35]: Why did you left it here? :cry:

**Review by tmiotto — APPROVED** [review]

File: lib/puppet/provider/oneview_network_set/c7000.rb [hunk 2]
```diff
@@ -14,30 +14,21 @@
...
     super(*args)
-    @client = OneviewSDK::Client.new(login)
-    api_version = login[:api_version] || 200
-    @resourcetype ||= if api_version == 200
-                        OneviewSDK::API200::NetworkSet
-                      else
-                        Object.const_get("OneviewSDK::API#{api_version}::C7000::NetworkSet")
-                      end
+    api_version ||= login[:api_version] || 200
     @ethernet ||= if api_version == 200
```
Comment (abiliogp) [inline lib/puppet/provider/oneview_network_set/c7000.rb]: Maybe "ethernet" could be changed by "ethernet_client" or something more specific.
