### PR TITLE
Interconnect API300 Support

### LINKED ISSUE #13: Interconnect API300 Support
### Scenario/Intent
Use Oneview_interconnect with API 300 on the Synergy and C7000 hardware variants

### Environment Details
 - **Puppet module for HPE OneView Version:** 2.0.0
 - **OneView SDK Version:** 3.0.0+
 - **OneView Appliance Version:** 3.0.0
 - **OneView Client API Version:** 300
 - **Puppet Version:** 4.0.0+
 - **Ruby Version:** 2.2.6
 - **Platform:** Windows/CentOS

### Steps to Reproduce
1- Create a login file with api_version = 300 and hardware_variant = "C7000" or "Synergy"
2- Create a manifest in which I call the Oneview_interconnect resource

### Expected Result
Should use the API 300 of the chosen hardware variant to perform any actions

### Actual Result
Uses the API 200 of the C7000 hardware variant to perform all actions.

### PR DESCRIPTION
**Pull request by fgbulsoni**
### Description
Extends support to API300 Synergy and C7000 for the Oneview_interconnect type

### Issues Resolved
#13 

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass (`$ rake test`).
- [X] New functionality has been documented in the README if applicable.
  - [X] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [X] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: lib/puppet/provider/oneview_interconnect/c7000.rb [hunk 1]
```diff
@@ -14,26 +14,30 @@
...
     super(*args)
-    @client = OneviewSDK::Client.new(login)
-    @resourcetype = OneviewSDK::Interconnect
-    @data = {}
   end
 
   def exists?
     @data = data_parse
-    empty_data_check([:found, :get_types])
+    puts resource['ensure']
```
Comment (tmiotto) [inline lib/puppet/provider/oneview_interconnect/c7000.rb]: puts in the `èxists?`

File: spec/shared_context.rb [hunk 2]
```diff
@@ -23,7 +23,7 @@
   JSON.parse(File.read(File.absolute_path(ENV['ONEVIEW_INTEGRATION_CONFIG'])), symbolize_names: true)
   JSON.parse(File.read(File.absolute_path(ENV['ONEVIEW_INTEGRATION_SECRETS'])), symbolize_names: true)
 rescue Errno::ENOENT
-  puts 'bla'
+  puts 'No Integration Config and/or Secrets files have been found. Intergration tests will not be able to run.'
```
Comment (tmiotto) [inline spec/shared_context.rb]: Why `puts` and not `raise`?

File: spec/unit/provider/oneview_interconnect_synergy_spec.rb [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+      allow_any_instance_of(resourcetype).to receive(:statistics).and_return('Test')
+      expect(provider.get_statistics).to be
+    end
+
+    it 'should be able to get the statistics' do
+      resource['data']['statistics'] = {}
+      resource['data']['statistics']['portName'] = 'portname'
+      resource['data']['statistics']['subportNumber'] = 'subportname'
+      allow_any_instance_of(resourcetype).to receive(:statistics).and_return('Test')
+      provider.exists?
```
Comment (tmiotto) [inline spec/unit/provider/oneview_interconnect_synergy_spec.rb:75]: Does `exists?` return only **true** or **false**? If so, why is it here?

**Review by tmiotto — CHANGES_REQUESTED** [review]

File: spec/unit/provider/oneview_interconnect_synergy_spec.rb (hunk 3 above)
Comment (fgbulsoni) [reply spec/unit/provider/oneview_interconnect_synergy_spec.rb:75]: exists? only returns true/false, but it's the first moment in which we can access the data inside the manifest. 
We need to always run exists? before other methods in spec because we also assign the value of @data there, and it's the behavior of puppet to always go through exists then onto the other provider methods.

**Review by tmiotto — APPROVED** [review]
