### PR TITLE
Fix volume attachment test

### LINKED ISSUE #119: Update unit tests to match updated remove_extra_unmanaged_volume from oneview-ruby-sdk
### Scenario/Intent
The build is failing. 

Unit Test from remove_extra_unmanaged_volume method must be fixed due to a recent change on the oneview-sdk-ruby.

The method remove_extra_unmanaged_volume from Volume Attachment was recently changed, and the unit test suite is failing. The changed method must be mocked instead of the internals rest calls.

### Environment Details
 - **Puppet module for HPE OneView Version:** Build
 - **OneView SDK Version:** Any
 - **OneView Appliance Version:** Any
 - **OneView Client API Version:** Any
 - **Puppet Version:** Any
 - **Ruby Version:** Any
 - **Platform:** Any

### Steps to Reproduce
rake test

### Expected Result
Build must pass.

### Actual Result
Build is failing.

### PR DESCRIPTION
**Pull request by abiliogp**
### Description
Fix Volume Attachment test

### Issues Resolved
#119

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: spec/unit/provider/oneview_volume_attachment_c7000_spec.rb [hunk 1]
```diff
@@ -14,15 +14,15 @@
...
-resourcetype ||= if api_version == 200
-                   OneviewSDK::API200::VolumeAttachment
-                 else
-                   Object.const_get("OneviewSDK::API#{api_version}::C7000::VolumeAttachment")
-                 end
+resource_name = 'VolumeAttachment'
+resourcetype = Object.const_get("OneviewSDK::API#{api_version}::C7000::#{resource_name}") unless api_version < 300
 
-describe provider_class, unit: true do
+describe provider_class, unit: true, if: login[:api_version] >= 300 do
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_volume_attachment_c7000_spec.rb]: Why only run when api >= 300?

File: spec/unit/provider/oneview_volume_attachment_c7000_spec.rb [hunk 2]
```diff
@@ -14,15 +14,15 @@
...
+
 provider_class = Puppet::Type.type(:oneview_volume_attachment).provider(:c7000)
+
 api_version = login[:api_version] || 200
-resourcetype ||= if api_version == 200
-                   OneviewSDK::API200::VolumeAttachment
-                 else
-                   Object.const_get("OneviewSDK::API#{api_version}::C7000::VolumeAttachment")
-                 end
+resource_name = 'VolumeAttachment'
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_volume_attachment_c7000_spec.rb]: These could likely be moved to line 26~27 for less clutter

File: spec/unit/provider/oneview_volume_attachment_synergy_spec.rb [hunk 3]
```diff
@@ -13,6 +13,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 ################################################################################
+require 'spec_helper'
 
 provider_class = Puppet::Type.type(:oneview_volume_attachment).provider(:synergy)
```
Comment (fgbulsoni) [inline spec/unit/provider/oneview_volume_attachment_synergy_spec.rb]: Could move lines 20-22 to line ~27 so those do not get run unless we are actually running the tests (a.k.a. using api version >= 300)

**Review by fgbulsoni — CHANGES_REQUESTED** [review]
Missing CHANGELOG

**Review by fgbulsoni — APPROVED** [review]
