### PR TITLE
Unit tests updated for ruby v2.4 and above.

### LINKED ISSUE #172: Unit Test cases are failing for resources on ruby version 2.4
### Scenario/Intent
Unit Test cases are failing for resources Enclosure and Logical Interconnect on ruby version 2.4 and above.

### Environment Details
 - **Puppet module for HPE OneView Version: 2.2.3
 - **OneView SDK Version: 5.5.0
 - **OneView Appliance Version: 4.00
 - **OneView Client API Version: 600
 - **Puppet Version: 5.5.1
 - **Ruby Version: 2.4.3
 - **Platform: Ubuntu 16.04 LTS

### Steps to Reproduce
run: rake spec

### Expected Result
Unit test completed without errors.

### Actual Result
Unit test errors in resources Enclosure and Logical Interconnect

### PR DESCRIPTION
**Pull request by jyothisgm**
### Description
Unit Test cases fixed for resources Enclosure and Logical Interconnect for ruby v 2.4 and above.

### Issues Resolved
#172 

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [X] Changes are documented in the CHANGELOG.

### CODE REVIEW

**Review by madhav-bharadwaj — APPROVED** [review]

**Review by soodpr — APPROVED** [review]
LGTM 👍

File: spec/unit/provider/oneview_logical_interconnect_spec.rb [hunk 1]
```diff
@@ -74,6 +75,7 @@
     end
 
     it 'return false when the resource does not exists' do
+      allow_any_instance_of(resource_type).to receive(:retrieve!).and_return(true)
```
Comment (sijeesh) [inline spec/unit/provider/oneview_logical_interconnect_spec.rb]: Its a duplication as you already added this line to before(:each) block that will run before all the test cases under the context.
Applicable for line number 78, 88, 115
