### PR TITLE
Unmanaged Devices API300 Support

### LINKED ISSUE #31: Unmanaged Device API300 Support
### Scenario/Intent
Use Oneview_unmanaged_device with API 300 on the Synergy and C7000 hardware variants

### Environment Details
 - **Puppet module for HPE OneView Version:** 2.0.0
 - **OneView SDK Version:** 3.0.0+
 - **OneView Appliance Version:** 3.0.0
 - **OneView Client API Version:** 300
 - **Puppet Version:** 4.0.0+
 - **Ruby Version:** 2.2.6
 - **Platform:** Windows/CentOS

### Steps to Reproduce
1- Create a login file with api_version = 300 and hardware_variant = "C7000" or "Synergy"
2- Create a manifest in which I call the Oneview_unmanaged_device resource

### Expected Result
Should use the API 300 of the chosen hardware variant to perform any actions

### Actual Result
Uses the API 200 of the C7000 hardware variant to perform all actions.

### PR DESCRIPTION
**Pull request by fgbulsoni**
### Description
Extends support to API300 Synergy and C7000 for the Oneview_unamanged_devices type

### Issues Resolved
#31 

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass (`$ rake test`).
- [X] New functionality has been documented in the README if applicable.
  - [X] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [X] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: lib/puppet/provider/oneview_unmanaged_device/synergy.rb [hunk 1]
```diff
@@ -0,0 +1,26 @@
+################################################################################
+# (C) Copyright 2016 Hewlett Packard Enterprise Development LP
```
Comment (tmiotto) [inline lib/puppet/provider/oneview_unmanaged_device/synergy.rb]: 2017?

File: spec/integration/provider/oneview_unmanaged_device_synergy_spec.rb [hunk 2]
```diff
@@ -0,0 +1,63 @@
+################################################################################
+# (C) Copyright 2016 Hewlett Packard Enterprise Development LP
```
Comment (tmiotto) [inline spec/integration/provider/oneview_unmanaged_device_synergy_spec.rb]: 2017?

**Review by tmiotto — CHANGES_REQUESTED** [review]

**Review by tmiotto — APPROVED** [review]
